name: AUTO MERGE DRIVE DAN MEGA IO

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'Masukkan URL (Pisahkan dengan koma)'
        required: true
        type: textarea

jobs:
  proses:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg megatools
          pip install gdown
          mkdir -p downloads ready

      - name: Download & Normalize
        run: |
          URLS=$(echo "${{ github.event.inputs.urls }}" | tr ',' ' ')
          count=1
          for url in $URLS; do
            # Download
            if [[ "$url" == *"mega.nz"* ]]; then
              megadl "$url" --path "downloads/file_$count"
            else
              gdown "$url" -O "downloads/file_$count"
            fi
            
            # Normalisasi ke MP4 standar
            ffmpeg -y -i "downloads/file_$count" \
            -vf "scale=1280:720:force_original_aspect_ratio=increase,crop=1280:720" \
            -c:v libx264 -pix_fmt yuv420p -c:a aac -ar 44100 "ready/video_$count.mp4"
            
            count=$((count + 1))
          done

      - name: Merge Final
        run: |
          for f in $(ls -v ready/video_*.mp4); do echo "file '$(pwd)/$f'" >> list.txt; done
          ffmpeg -f concat -safe 0 -i list.txt -c copy output.mp4

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: output.mp4
