name: Render Video Engine

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL Visual (Link Direct .jpg/.mp4)'
        required: true
      audio_urls:
        description: 'URL Audio (Pisahkan link dengan SPASI)'
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Render Video
        run: |
          # Download visual
          wget -q --user-agent="Mozilla/5.0" -O visual_input "${{ github.event.inputs.video_url }}"
          
          # Download semua audio dan siapkan list untuk FFmpeg
          audio_links=(${{ github.event.inputs.audio_urls }})
          audio_inputs=""
          filter_complex=""
          
          for i in "${!audio_links[@]}"; do
            wget -q --user-agent="Mozilla/5.0" -O "audio_$i.mp3" "${audio_links[$i]}"
            audio_inputs="$audio_inputs -i audio_$i.mp3"
            filter_complex="${filter_complex}[$i:a]"
          done
          
          # Gabungkan semua audio menjadi satu stream
          num_audios=${#audio_links[@]}
          filter_complex="${filter_complex}concat=n=${num_audios}:v=0:a=1[outa]"
          
          # Proses FFmpeg
          file_type=$(file --mime-type -b visual_input)
          
          if [[ $file_type == image/* ]]; then
            ffmpeg -y -loop 1 -i visual_input $audio_inputs -filter_complex "$filter_complex" -map 0:v -map "[outa]" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p -shortest -preset ultrafast output.mp4
          else
            ffmpeg -y -i visual_input $audio_inputs -filter_complex "$filter_complex" -map 0:v -map "[outa]" -c:v copy -c:a aac -pix_fmt yuv420p -shortest -preset ultrafast output.mp4
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-hasil
          path: output.mp4
          
