name: Download from HF and Upload to YouTube

on:
  workflow_dispatch:
    inputs:
      jobId:
        description: "ID Job dari Hugging Face"
        required: true
      videoTitle:
        description: "Judul Video"
        required: true

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install googleapis

      - name: Download Video from Hugging Face
        run: |
          echo "Download Job: ${{ github.event.inputs.jobId }}"

          curl -L \
            -o video.mp4 \
            "https://ferdyankuya-ytshortsku-long.hf.space/api/download-result/${{ github.event.inputs.jobId }}"

          if [ ! -s video.mp4 ]; then
            echo "Video kosong atau gagal didownload"
            exit 1
          fi

          echo "Ukuran file:"
          du -sh video.mp4

      - name: Upload to YouTube
        env:
          CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          VIDEO_TITLE: ${{ github.event.inputs.videoTitle }}
        run: |
          node upload.js
